export const category = [
  { id: 0, title: "회사소개", path: "" },
  { id: 1, title: "투자 IR", path: "" },
  { id: 2, title: "M&A", path: "" },
  { id: 3, title: "IPO", path: "" },
  { id: 4, title: "해외진출", path: "" },
  { id: 5, title: "기술거래", path: "" },
];

export const subCategory = {
  회사소개: [
    { title: "인사말", path: "" },
    { title: "컨설팅 서비스 분야", path: "" },
    { title: "컨설턴트 소개", path: "" },
    { title: "주요 경제 신문 보도기사", path: "" },
    { title: "CI", path: "" },
    { title: "인증 및 수상내역", path: "" },
  ],
  "투자 IR": [
    { title: "투자IR 컨설팅 개요", path: "" },
    { title: "투자IR 사업계획서", path: "" },
    { title: "네트워크를 활용 컨설팅", path: "" },
    { title: "컨설팅 진행 절차", path: "" },
    { title: "투자유치 성공사례", path: "" },
    { title: "컨설팅 신청", path: "" },
  ],
  "M&A": [
    { title: "M&A 개요", path: "" },
    { title: "M&A 분류", path: "" },
    { title: "M&A 목적", path: "" },
    { title: "우회 상장", path: "" },
    { title: "M&A 거래정보", path: "" },
    { title: "M&A 보증지원", path: "" },
    { title: "M&A 중개지원", path: "" },
  ],
  IPO: [
    { title: "상장의 개요", path: "" },
    { title: "상장의 혜택 및 효과", path: "" },
    { title: "유가증권 시장 상장", path: "" },
    { title: "코스닥 시장 상장", path: "" },
    { title: "SPAC 우회 상장", path: "" },
    { title: "IOP 절차", path: "" },
  ],
  해외진출: [
    { title: "해외진출 사업 소개", path: "" },
    { title: "제타플랜 해외네트워크", path: "" },
    { title: "해외지사화사업", path: "" },
    { title: "해외시장조사", path: "" },
    { title: "해외법인설립", path: "" },
    { title: "글로벌기술사업화(중국)", path: "" },
  ],
  기술거래: [
    { title: "기술거래 개요", path: "" },
    { title: "기술거래 절차", path: "" },
    { title: "국내외 협력기관", path: "" },
    { title: "국내외 기술거래 사진", path: "" },
    { title: "자료실", path: "" },
    { title: "기술거래 리스트", path: "" },
    { title: "도입희망기술등록", path: "" },
  ],
};
