// continent 0 : 유럽, 1 : 아시아, 2 : 아프리카
export const nations = [
  {
    id: 0,
    continent: 0,
    name_eng: "Europe",
    name_kor: "유럽",
    flag: "china_flag",
    lat: 46.227638,
    lng: 2.213749,
    networks: [
      {
        name: "주한영국상공회의소(BCCK)",
        detail:
          "한국 상공 영국 상공 회의소 (BCCK)는 모든 국적의 개인과 기업에 열려 한국의 주요 국제 및 지역 비즈니스 포럼",
        intro_link: "",
        logo: "europe1",
      },
      {
        name: "ENTERPRISE EUROPE NETWORK(EEN)",
        detail: "유럽위원회가 중소기업 지원을 위해 운영하는 핵심조직",
        intro_link: "",
        logo: "europe2",
      },
      {
        name: "GLE TUVRheinland",
        detail:
          "모든 대륙에 69 개국에서 작용하는 선도적인 국제 서비스 제공 그룹",
        intro_link: "",
        logo: "europe3",
      },
      {
        name: "핀란드 상공회의소(FINNCHAM)",
        detail: "중소기업의 국제화 지원을 위한 우수한 채널 제공",
        intro_link: "",
        logo: "europe4",
      },
    ],
  },
  {
    id: 1,
    continent: 1,
    flag: "china_flag",
    name_eng: "CHINA",
    name_kor: "중국",
    lat: 35.86166,
    lng: 104.195397,
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        intro_link: "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange,dasdass dasddasdas",
        intro_link: "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        intro_link: "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
    ],
  },
  {
    id: 2,
    continent: 1,
    flag: "china_flag",
    name_eng: "Vietnam",
    name_kor: "베트남",
    lat: 14.058324,
    lng: 108.277199,
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 3,
    continent: 1,
    flag: "china_flag",
    name_eng: "Singapore",
    name_kor: "싱가포르",
    lat: 1.352083,
    lng: 103.819836,
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 4,
    continent: 1,
    flag: "china_flag",
    name_eng: "Malaysia",
    name_kor: "말레이시아",
    lat: 4.210484,
    lng: 101.975766,
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 5,
    continent: 1,
    flag: "china_flag",
    name_eng: "Japan",
    name_kor: "일본",
    lat: 36.204824,
    lng: 138.252924,
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 6,
    continent: 1,
    flag: "china_flag",
    name_eng: "Indonesia",
    name_kor: "인니",
    lat: -0.789275,
    lng: 113.921327,
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },

  {
    id: 7,
    continent: 2,
    flag: "china_flag",
    name_eng: "Africa1",
    name_kor: "아프리카1",
    networks: [],
  },
];
