// continent 0 : 유럽, 1 : 아시아, 2 : 아프리카
export const nations = [
  {
    id: 0,
    continent: 0,
    name_eng: "France",
    name_kor: "프랑스",
    networks: [
      {
        name: "프랑스임ICI",
        detail: "Beijing B&R International Co-incubation",
        intro_link: "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange,dasdass dasddasdas",
        intro_link: "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        intro_link: "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
    ],
  },
  {
    id: 1,
    continent: 0,
    name_eng: "United Kingdom",
    name_kor: "영국",
    networks: [],
  },
  {
    id: 2,
    continent: 0,
    name_eng: "United Kingdom",
    name_kor: "영국2",
    networks: [],
  },
  {
    id: 3,
    continent: 0,
    name_eng: "United Kingdom",
    name_kor: "영국3",
    networks: [],
  },
  {
    id: 4,
    continent: 1,
    name_eng: "CHINA",
    name_kor: "중국",
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        intro_link: "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange,dasdass dasddasdas",
        intro_link: "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        intro_link: "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        intro_link: "",
        logo: "china5",
      },
    ],
  },
  {
    id: 5,
    continent: 1,
    name_eng: "Vietnam",
    name_kor: "베트남",
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 6,
    continent: 1,
    name_eng: "Singapore",
    name_kor: "싱가포르",
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 7,
    continent: 1,
    name_eng: "Malaysia",
    name_kor: "말레이시아",
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 8,
    continent: 1,
    name_eng: "Japan",
    name_kor: "일본",
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },
  {
    id: 9,
    continent: 1,
    name_eng: "Indonesia",
    name_kor: "인니",
    networks: [
      {
        name: "ICI",
        detail: "Beijing B&R International Co-incubation",
        "intro-link": "",
        logo: "china1",
      },
      {
        name: "베이징기술교역촉진중심",
        detail: "Beijing Technology Transfer & Exchange, ...",
        "intro-link": "",
        logo: "china2",
      },
      {
        name: "상하이기술교역소",
        detail: "Shanghai Technology Transfer & Exchange Center",
        "intro-link": "",
        logo: "china3",
      },
      {
        name: "절강성과학기술교류중심",
        detail: "Zhejang Provincial and Technology Center...",
        "intro-link": "",
        logo: "china4",
      },
    ],
  },

  {
    id: 10,
    continent: 2,
    name_eng: "Africa1",
    name_kor: "아프리카1",
    networks: [],
  },
  {
    id: 11,
    continent: 2,
    name_eng: "Africa2",
    name_kor: "아프리카2",
    networks: [],
  },
  {
    id: 12,
    continent: 2,
    name_eng: "Africa3",
    name_kor: "아프리카3",
    networks: [],
  },
  {
    id: 13,
    continent: 2,
    name_eng: "Africa4",
    name_kor: "아프리카4",
    networks: [],
  },
  {
    id: 13,
    continent: 2,
    name_eng: "Africa5",
    name_kor: "아프리카5",
    networks: [],
  },
];
